config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  resources :users
  resources :todos
  post "/user/logout" => "sessions#logout", as: "logout"
  get "/user/signin" => "sessions#signin", as: "sign_in"
  post "/user/signin" => "sessions#login"
  post "/todo/:id/toggle" => "todos#toggle", as: "toggle"
  get "/admin/:id/controls" => "admin#show", as: "admin"
  get "/admin/:id/show/users" => "admin#show_users", as: "show_users"
  get "/admin/:admin_id/user/:user_id" => "admin#inspect_user", as: "inspect_user"
  post "/admin/:admin_id/delete/todo/:todo_id" => "admin#delete_todo", as: "delete_todo"
  post "/admin/:admin_id/remove/user/:user_id" => "admin#remove_user", as: "remove_user"
  post "/admin/:admin_id/assign/admin/user/:user_id" => "admin#assign_admin", as: "assign_admin"
  post 'braintree/checkout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	mount_uploaders :avatars, AvatarUploader
	belongs_to :user
	validates :description, presence: true

	def check
		self.status = true
		self.save
	end

	def uncheck
		self.status = false
		self.save
	end
end

app/models/user.rb
class User < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	has_many :todos, dependent: :destroy
	has_secure_password
	validates :email, uniqueness: true
	validates :email, :uniqueness=> true, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => "error"}
	validates :first_name, :last_name, :password, :password_confirmation, :email, presence: true, on: [:create]
	
	enum position: [:user, :admin]

	def name
		self.first_name + " " + self.last_name
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :require_login

	def show
		@admin = User.find(params[:id])
		if current_user.id != @admin.id
			redirect_to root_path
		end
	end

	def show_users
		@admin = User.find(params[:id])
		if current_user.id == @admin.id
			@users = User.all
		else
			redirect_to root_path
		end
	end

	def inspect_user
		@admin = User.find(params[:admin_id])
		if current_user.id == @admin.id
			@user = User.find(params[:user_id])
		else
			redirect_to root_path
		end
	end

	def delete_todo
		@admin = User.find(params[:admin_id])
		if current_user.id == @admin.id
			@todo = Todo.find(params[:todo_id])
			@user = User.find(@todo.user_id)
			@todo.destroy
			redirect_to inspect_user_path(admin_id: @admin.id, user_id: @user.id)
		else
			redirect_to root_path
		end
	end

	def remove_user
		@admin = User.find(params[:admin_id])
		if current_user.id == @admin.id
			@user = User.find(params[:user_id])
			@user.destroy
			redirect_to show_users_path(id: @admin.id)
		else
			redirect_to root_path
		end
	end

	def assign_admin
		@admin = User.find(params[:admin_id])
		if current_user.id == @admin.id
			@user = User.find(params[:user_id])
			@user.position = 1
			@user.save
			redirect_to show_users_path(id: @admin.id)
		else
			redirect_to root_path
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UsersHelper

	def require_login
		unless session[:current_user_id]
			render "welcome/index"
		end
	end
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
  	@user = User.find(params[:id])
  	@client_token = Braintree::ClientToken.generate
  end

  def checkout
	  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

	  result = Braintree::Transaction.sale(
	   :amount => "0.99",
	   :payment_method_nonce => nonce_from_the_client,
	   :options => {
	      :submit_for_settlement => true
	    }
	   )

	  if result.success?
	  	@user = User.find(params[:id])
	  	@user.update!(paid: true)
	  	redirect_to @user
	  end 
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def signin
	end

	def login
		if params[:session][:password] == params[:session][:password_confirmation]
			if @user = User.find_by(email: params[:session][:email])
				if @user.authenticate(params[:session][:password])
					session[:current_user_id] = @user.id
					redirect_to @user
				else
					render 'signin'
				end
			else
				render 'signin'
			end
		else
			render 'signin'
		end	

	end

	def logout
		session.destroy
		redirect_to root_path
	end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :require_login

	def new
		@todo = Todo.new
		unless current_user.position == "admin" || current_user.paid == true || current_user.todos.count < 5
			redirect_to current_user
		end
	end

	def create
		if current_user.todos.count < 5 || current_user.paid == true || current_user.position == "admin"
			@todo = current_user.todos.new(description: params[:todo][:description])
			if @todo.save
				if todo_pictures
					assign_todo_pictures
				end
				redirect_to current_user
			else
				render 'new'
			end
		else
			redirect_to current_user
		end
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def update
		@todo = Todo.find(params[:id])
		if @todo.user_id == current_user.id
			if @todo.update(description: params[:todo][:description])
				if todo_pictures
					assign_todo_pictures
				end
				redirect_to current_user
			else
				render 'edit'
			end
		else
			redirect_to root_path
		end
	end

	def destroy
		@todo = Todo.find(params[:id])
		if @todo.user_id == current_user.id
			@todo.destroy
			redirect_to current_user
		else
			redirect_to root_path
		end
	end

	def toggle
		@todo = Todo.find(params[:id])
		if @todo.user_id == current_user.id
			if @todo.status == true
				@todo.uncheck
			else
				@todo.check
			end
		end
		render json: @todo
	end

	private
	def todo_pictures
		params[:todo][:avatars]
	end

	def assign_todo_pictures
		@todo.avatars = todo_pictures
		@todo.save!
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, only: [:show, :edit, :update]

	def new
		@user = User.new
	end

	def create
		@user = User.new(create_user_params)
		if @user.save
			if user_picture
				assign_user_picture
			end
			redirect_to sign_in_path
		else
			render "new"
		end
	end

	def show
		@user = User.find(params[:id])
		if params[:filter] == "true"
			@todos = Todo.where(user_id: params[:id], status: true)
		elsif params[:filter] == "false"
			@todos = Todo.where(user_id: params[:id], status: false)
		else
			@todos = Todo.where(user_id: params[:id])
		end
		@todos = @todos.order(:status, :description)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.id == current_user.id
			if @user.update(edit_user_params)
				if user_picture
					assign_user_picture
				end
				redirect_to @user
			else
				render 'edit'
			end
		else
			redirect_to root_path
		end
	end

	private
	def create_user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

	def edit_user_params
		params.require(:user).permit(:first_name, :last_name)
	end

	def user_picture
		params[:user][:avatar]
	end

	def assign_user_picture
		@user.avatar = user_picture
		@user.save!
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		if session[:current_user_id]
			redirect_to current_user
		end
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		User.find(session[:current_user_id])
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/inspect_user.html.erb
<h1>Inspecting as: <%= @admin.name %></h1>
<%= @user.name %><br>
<%= @user.email %>
<% if @user.todos.count != 0 %>
	<table>
		<tr>
			<th>No.</th>
			<th>Images</th>
			<th>Description</th>
			<th>Completion</th>
			<th>Actions</th>
		</tr>
		<% @user.todos.each_with_index do |todo,index| %>
			<tr>
				<td><%= index + 1 %>.</td>
				<td>
				<% if todo.avatars.count != 0 %>
					<% todo.avatars.each_with_index do |avatar,index2| %>
						<a href= <%= avatar.url %> ><img style="width: 100px;" src= <%= avatar.url %> ></a>
						<% if index2.odd? %>
							<br>
						<% end %>
					<% end %>
				<% else %>
					No images
				<% end %>
				</td>
				<td><%= todo.description %></td>
				<td><%= todo.status.to_s.capitalize %></td>
				<td><%= link_to "Delete", delete_todo_path(todo_id: todo.id, admin_id: @admin.id), data: { confirm: "Are you sure?" }, method: :post %></td>
			</tr>
		<% end %>
	</table>
<% end %>
<% unless @user.position == "admin" %>
	<br><%= link_to "Assign admin", assign_admin_path(user_id: @user.id, admin_id: @admin.id), method: :post %>
<% end %>
<% if @user.id != @admin.id %>
<br><%= link_to "Remove User", remove_user_path(admin_id: @admin.id, user_id: @user.id), method: :post, data: { confirm: "Are you sure?" } %>
<% end %>
<br><%= link_to "Back", show_users_path(id: @admin.id) %>

app/views/admin/show.html.erb
<h1>Admin Page</h1>
<h1><%= @admin.name %></h1>
<%= link_to "Show Users", show_users_path(id: @admin.id) %><br>
<%= link_to "Back", user_path(@admin) %>

app/views/admin/show_users.html.erb
<% if @users.count != 0 %>
	<ol type="I" >
		<% @users.each do |user| %>
			<li><%= link_to "#{user.name}", inspect_user_path(admin_id: @admin.id, user_id: user.id) %> : 
			<% if user.position == "user" %>
				User
			<% else %>
				Admin
			<% end %>
			</li>
		<% end %>
	</ol>
<% end %>
<%= link_to "Back", admin_path(id: @admin.id) %>

app/views/braintree/new.html.erb
<div class="demo-frame">  

  <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>      
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce",id: "nonce" %>
    <input type="hidden" name="id" value=<%= @user.id %>>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "button" %>
    </div>
  <% end %>
</div>
<br><%= link_to "Back", user_path(@user) %>
<script type="text/javascript">
var form = document.querySelector('#cardForm');
var submit = document.querySelector('input[type="submit"]')
var authorization = '<%= @client_token %>';

braintree.client.create({
        authorization: authorization
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          console.error(clientErr);
          return;
        }

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14px'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
            number: {
              selector: '#card-number',
              placeholder: '4111 1111 1111 1111'
            },
            cvv: {
              selector: '#cvv',
              placeholder: '123'
            },
            expirationDate: {
              selector: '#expiration-date',
              placeholder: '10/2019'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            console.error(hostedFieldsErr);
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();

            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }
              document.querySelector("#nonce").value = payload.nonce
              form.submit()
            });
          }, false);
        });
      });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo lister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
	<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_edit.html.erb
<%= form_for @todo do |t| %>
	<%= t.file_field :avatars, multiple: true %>
	<%= t.text_field :description %>
	<%= t.submit "Edit" %>
<% end %>

app/views/todos/_new.html.erb
<%= form_for @todo do |t| %>
	<%= t.file_field :avatars, multiple: true %>
	<%= t.text_field :description, placeholder: "Description" %>
	<%= t.submit "Create" %>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit To Do</h1>
<%= render 'edit' %>
<%= link_to "Back", user_path(current_user) %>

app/views/todos/new.html.erb
<h1>New To Do</h1>
<%= render 'new' %>
<%= link_to "Back", user_path(current_user) %>

app/views/users/_edit.html.erb
<%= form_for @user do |u| %>
	<%= u.file_field :avatar %>
	<%= u.text_field :first_name %>
	<%= u.text_field :last_name %>
	<%= u.submit "Edit" %>
<% end %>

app/views/users/_new.html.erb
<%= form_for @user do |u| %>
	<%= u.file_field :avatar %>
	<%= u.text_field :first_name, placeholder: "First Name" %>
	<%= u.text_field :last_name, placeholder: "Last Name" %>
	<%= u.text_field :email, placeholder: "E-mail" %>
	<%= u.password_field :password, placeholder: "Password" %>
	<%= u.password_field :password_confirmation, placeholder: "Password Confirmation" %>
	<%= u.submit "Sign Up" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'edit' %>
<%= link_to "Back", user_path(@user) %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "new" %>
<%= link_to "Back", root_path %>

app/views/users/show.html.erb
<% if !@user.avatar.file.nil? %>
	<img style="height: 100px;" src= <%= @user.avatar.url %> >
<% end %>
<h1><%= @user.name %></h1>
<%= link_to "Edit", edit_user_path(@user) %><br>
<% if params[:filter] == nil %>
	<%= link_to "Not Complete", user_path(@user, filter: false) %><br>
	<%= link_to "Completed", user_path(@user, filter: true) %><br>
<% elsif params[:filter] == "false" %>
	<%= link_to "All", user_path(@user) %><br>
	<%= link_to "Completed", user_path(@user, filter: true) %><br>
<% elsif params[:filter] == "true" %>
	<%= link_to "All", user_path(@user) %><br>
	<%= link_to "Not Complete", user_path(@user, filter: false) %><br>
<% end %>
<% if @todos.count != 0 %>
	<table>
		<tr>
			<th>No.</th>
			<th>Images</th>
			<th>Description</th>
			<th>Completion</th>
			<th>Actions</th>
		</tr>
		<% @todos.each_with_index do |todo,index| %>
			<tr>
				<td><%= index + 1 %>.</td>
				<td>
				<% if todo.avatars.count != 0 %>
					<% todo.avatars.each_with_index do |avatar,index2| %>
						<a href= <%= avatar.url %> ><img style="width: 100px;" src= <%= avatar.url %> ></a>
						<% if index2.odd? %>
							<br>
						<% end %>
					<% end %>
				<% else %>
					No images
				<% end %>
				</td>
				<td><%= todo.description %></td>
				<td><%= link_to "#{todo.status}", toggle_path(id: todo.id), style: "text-decoration: none; color: blue;", class: "toggle", remote: true, id: "#{todo.id}", method: :post %></td>
				<td><%= link_to "Edit", edit_todo_path(todo) %> <%= link_to "Delete", todo_path(todo), method: :delete, data: { confirm: "Are you sure?" } %></td>
			</tr>
		<% end %>
	</table>
<% elsif params[:filter] %>
<% else %>
	You have no Todos for now.
<% end %>
<% if @user.position == "admin" || @user.paid == true || @user.todos.count < 5 %>
	<br><%= link_to "New todo", new_todo_path %>
<% else %>
	<br><%= link_to "Pay 0.99 USD to create unlimited todos.", braintree_new_path(id: @user.id) %>
<% end %>
<% if @user.position == "admin" %>
	<br><%= link_to "Admin Page", admin_path(id: @user.id), data: { no_turbolink: true } %>
<% end %>
<br><%= link_to "Log Out", logout_path, method: :post %><br>
<%= request.location.city %>

app/views/welcome/index.html.erb
Todo Lister
<%= link_to "Sign Up", new_user_path %>
<%= link_to "Sign In", sign_in_path %>